name: Issue greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 你好 @${{ github.actor }}，感谢你对 ImageMarker —— 免费在线的照片标注工具 的关注！🏷️

            ## 🐞 Bug 反馈

            如果你发现 ImageMarker 工作不正常，请尽可能提供详细信息（浏览器类型、Node 版本、操作步骤等），这能帮助我们更快地定位并解决问题。😉

            ## 💬 联系我们

            如果你提交了 issue 但一直没有收到回复，请通过 GitHub Issues 再次联系我们：[https://github.com/FasterEdge/ImageMarker/issues](https://github.com/FasterEdge/ImageMarker/issues)

            ## 💻 本地运行

            ```bash
            # 克隆仓库
            git clone https://github.com/FasterEdge/ImageMarker.git

            # 进入主目录
            cd ImageMarker

            # 安装依赖
            npm install

            # 在 localhost:3000 启动并支持热重载
            npm start
            ```
            为确保应用在本地正常运行，需要 npm `8.x.x` 和 node.js `v16.x.x` 版本。
